const INTERNAL_SERVER_ERROR = 500;
const BAD_REQUEST = 400;
const NOT_FOUND = 404;
const UNAUTHORIZED_ERROR = 401;
const FORBIDDEN = 403;
const CONFLICT = 409;

module.exports = {
  INTERNAL_SERVER_ERROR,
  BAD_REQUEST,
  NOT_FOUND,
  UNAUTHORIZED_ERROR,
  FORBIDDEN,
  CONFLICT,
};
